### ISSUE TITLE
complete_example is not compilable: still uses freezed models

### ISSUE THREAD

**Issue by agordeev** [lucavenir/go_router_riverpod#13]
Compile fails on using `UserRole.none()`. Seems you forgot to replace it by enum?

PS: `RedirecttionBasedOnRole` has a typo :)

**Comment by lucavenir** [comment]
I might have copy-pasted badly that example. I'm too addicted to code gen, ahah.

I'll look into it in the next week

**Comment by alexsuriya** [comment]
Hi @lucavenir , Do we have any updates on the issue fixes?

**Comment by lucavenir** [comment]
Hi, sorry about the delay.

Weirdly enough my IDE wasn't picking up this compile error. That's why it slipped away. I'll accept the PR asap
