### ISSUE TITLE
Complete example throws error

### ISSUE THREAD

**Issue by Kublick** [lucavenir/go_router_riverpod#16]
Got the complete example in order to check how it works but as soon you tap the login button it will throw an error on this function

```
 Future<void> login(String email, String password) async {
    state = await AsyncValue.guard<User>(() async {
      return Future.delayed(
        networkRoundTripTime,
        () =>
      );
    });
  }
```
in the console I can see
```
type 'AsyncData<User?>' is not a subtype of type 'AsyncValue<User>' of 'previous'
```

Removing <User> after guard resolves the issue.

**Comment by leedeblade** [comment]
Because AuthNotifier extends AutoDisposeAsyncNotifier<User?>, therefore, i think login functions should be: 
 Future<void> login(String email, String password) async {
    **state = await AsyncValue.guard<User?>(() async** {
      return Future.delayed(
        networkRoundTripTime,
        () =>
      );
    });
  }

**Comment by lucavenir** [comment]
Oddly enough, while this makes sense, this should be a compile-time error, which I don't have. Moreover, the example runs fine to me.

@Kublick please try out @leedeblade 's fix and let us know if it works.

**Comment by Kublick** [comment]
Indeed adding ? does the trick.
