### ISSUE TITLE
code_gen always ens up on homepage page, ignoring permissions

### ISSUE THREAD

**Issue by k2s** [lucavenir/go_router_riverpod#19]
Than you for this great repository.

`HomeRoute.redirect()` is called, but `if (state.location == HomeRoute.path) return null;` is always returns.
The method `_requestMock()` is never called.

If I comment `if (state.location == HomeRoute.path) return null;`, the `final userRole = roleListener.read();` will return with `null` before the `_requestMock()` method is called.

Could you please fix this?

PS: the `permissionsProvider` doesn't seam to work also in the complete example

**Comment by lucavenir** [comment]
> Than you for this great repository.

🙏🏼

> Could you please fix this?

On it.
