### ISSUE TITLE
Stupid question about private variables

### ISSUE THREAD

**Issue by jascodes** [lucavenir/go_router_riverpod#2]
Hi @lucavenir 
``` 
   ...
    redirect: router._redirect, // All the logic is centralized here
    routes: router._routes,
   ...
```

How come private variable _redirect and _routes are accessible? 

Thanks
Jas

**Comment by alaazamelDev** [comment]
> How come private variable _redirect and _routes are accessible?

Private fields are intended to be visible outside of the class in which they are declared. They are private to the library in which they are declared. See the explanation in the [Language Tour](https://dart.dev/guides/language/language-tour#libraries-and-visibility).

**Comment by jascodes** [comment]
Lol thanks!!
