### ISSUE TITLE
Auto Login dsnt work

### ISSUE THREAD

**Issue by tonyhart7** [lucavenir/go_router_riverpod#26]
auto login dsnt work with external api call

I been test codegen,complete and legacy, their work in test using sharedprefs. however when using external api call 
the token stored is always null and this been happen in 3 project with different example

**Comment by lucavenir** [comment]
I'm touching and updating the examples as of now, and they do work. Please be more specific and I'll reach you back in a new issue.

Also, consider that I'm maintaining `code_gen` only from now on.
