### ISSUE TITLE
I don't see a complete_example folder

### ISSUE THREAD

**Issue by ronytesler** [lucavenir/go_router_riverpod#28]
Where is the `complete_example` folder?

**Comment by TristanKing0** [comment]
He's only just changed it so hasn't updated the readme yet, use the example folder now, codegen is the default. Complete example is now in legacy.

**Comment by ronytesler** [comment]
Is there an example without hooks and without codegen?

**Comment by lucavenir** [comment]
> He's only just changed it

Omw to updating the README.

> Is there an example without hooks and without codegen?

It's kinda hard - to me - to maintain a duplicated deeply nested examples with these two / three / more approaches.
Keep in mind that conceptually there is literally no difference. It's just syntactic sugar.

Please check out the new example that collects and implement every request I've received and feel free to submit a PR with your favorite syntax.
