### ISSUE TITLE
Go router no longer provide location in GoRouterState after 9.0

### ISSUE THREAD

**Issue by at15** [lucavenir/go_router_riverpod#34]
I was using `state.location` in [redirect](https://github.com/lucavenir/go_router_riverpod/blob/master/firebase_example/lib/router.dart#L40) and found compile error after upgrade go router.

From https://pub.dev/packages/go_router/changelog

BREAKING CHANGE:

- Removes GoRouter.location. Use GoRouterState.of().location instead.
- GoRouter does not extends ChangeNotifier.
- [Migration guide](https://flutter.dev/go/go-router-v9-breaking-changes)

I tried updating the code with `GoRouterState.of(context).matchedLocation` but end up getting `There is no modal route above current context` like https://github.com/flutter/flutter/issues/130213

**Comment by at15** [comment]
Changed to `state.uri.path` seems works for redirect https://github.com/lucavenir/go_router_riverpod/blob/master/firebase_example/lib/router.dart#L40

**Comment by lucavenir** [comment]
Hi there, and thank you for filing this.
I'm fixing this ASAP.

**Comment by lucavenir** [comment]
Fixed
