### ISSUE TITLE
Suggested approach with more than one provider to watch? 

### ISSUE THREAD

**Issue by spakanati** [lucavenir/go_router_riverpod#7]
I have multiple providers that I need to watch to determine whether redirects are needed (e.g. auth provider, email verification provider, etc.). In that scenario using the new sync example, my screen visibly flashes when rebuilding multiple times. I did read [the README section](https://github.com/lucavenir/go_router_riverpod/tree/master/sync_router#wait-a-minute-i-do-see-unnecessary-rebuilds) about how most rebuilds aren't what they seem, but it seems the current approach may only be meant for a single provider at a time? When I remove everything but a single auth provider the behavior is as expected and there is no flickering or visible rebuilding. Is there a suggested approach or any examples showing how to watch more than one provider? Should I create a combined provider that has every bit of state/property the router needs for its redirect? Thanks so much for making this repo!

**Comment by lucavenir** [comment]
Sure.

I'll try to address this ASAP. Specifically, it depends on the use case, but maybe we can show off a even "more complete" example in which multiple states need to be listened to.

Unluckily, I am _very_ busy at the moment. I need to ask either for your patience (it's gonna take time) or for a PR to be reviewed and merged.

**Comment by lucavenir** [comment]
Hi again. I just updated the master branch, with several hotfixes. I wanted to fix some issues, to better document my choices and to simplify the codebase.

You can check the answer to your question in the new notifier I created, [here](https://github.com/lucavenir/go_router_riverpod/blob/master/complete_example/lib/router/router_notifier.dart) (read the `build` method).

If you have more questions, please let me know.
